[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "placement-center"
path = "src/placement-center/server.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }

